// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chat.proto

/*
Package chat is a generated protocol buffer package.

It is generated from these files:
	chat.proto

It has these top-level messages:
	Message
*/
package chat

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Message struct {
	Register bool   `protobuf:"varint,1,opt,name=register" json:"register,omitempty"`
	Close    bool   `protobuf:"varint,2,opt,name=close" json:"close,omitempty"`
	User     string `protobuf:"bytes,3,opt,name=user" json:"user,omitempty"`
	Data     string `protobuf:"bytes,4,opt,name=data" json:"data,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Message) GetRegister() bool {
	if m != nil {
		return m.Register
	}
	return false
}

func (m *Message) GetClose() bool {
	if m != nil {
		return m.Close
	}
	return false
}

func (m *Message) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *Message) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterType((*Message)(nil), "chat.Message")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ChatService service

type ChatServiceClient interface {
	Communicate(ctx context.Context, opts ...grpc.CallOption) (ChatService_CommunicateClient, error)
}

type chatServiceClient struct {
	cc *grpc.ClientConn
}

func NewChatServiceClient(cc *grpc.ClientConn) ChatServiceClient {
	return &chatServiceClient{cc}
}

func (c *chatServiceClient) Communicate(ctx context.Context, opts ...grpc.CallOption) (ChatService_CommunicateClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_ChatService_serviceDesc.Streams[0], c.cc, "/chat.ChatService/Communicate", opts...)
	if err != nil {
		return nil, err
	}
	x := &chatServiceCommunicateClient{stream}
	return x, nil
}

type ChatService_CommunicateClient interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ClientStream
}

type chatServiceCommunicateClient struct {
	grpc.ClientStream
}

func (x *chatServiceCommunicateClient) Send(m *Message) error {
	return x.ClientStream.SendMsg(m)
}

func (x *chatServiceCommunicateClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for ChatService service

type ChatServiceServer interface {
	Communicate(ChatService_CommunicateServer) error
}

func RegisterChatServiceServer(s *grpc.Server, srv ChatServiceServer) {
	s.RegisterService(&_ChatService_serviceDesc, srv)
}

func _ChatService_Communicate_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChatServiceServer).Communicate(&chatServiceCommunicateServer{stream})
}

type ChatService_CommunicateServer interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ServerStream
}

type chatServiceCommunicateServer struct {
	grpc.ServerStream
}

func (x *chatServiceCommunicateServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func (x *chatServiceCommunicateServer) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _ChatService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "chat.ChatService",
	HandlerType: (*ChatServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Communicate",
			Handler:       _ChatService_Communicate_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "chat.proto",
}

func init() { proto.RegisterFile("chat.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 165 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x54, 0x8e, 0x3d, 0x0e, 0x82, 0x40,
	0x10, 0x46, 0x5d, 0x45, 0xc5, 0x21, 0x36, 0x13, 0x8b, 0x0d, 0x15, 0xa1, 0xa2, 0x22, 0xfe, 0x5c,
	0xc0, 0x84, 0xda, 0x06, 0x4f, 0x30, 0xae, 0x13, 0x20, 0x11, 0xd7, 0xec, 0x0e, 0x9e, 0xdf, 0xb0,
	0x18, 0x13, 0xbb, 0xf7, 0xbe, 0xaf, 0x79, 0x00, 0xa6, 0x25, 0x29, 0x5f, 0xce, 0x8a, 0xc5, 0x68,
	0xe4, 0xdc, 0xc0, 0xfa, 0xc2, 0xde, 0x53, 0xc3, 0x98, 0x42, 0xec, 0xb8, 0xe9, 0xbc, 0xb0, 0xd3,
	0x2a, 0x53, 0x45, 0x5c, 0xff, 0x1c, 0x77, 0xb0, 0x34, 0x0f, 0xeb, 0x59, 0xcf, 0xc3, 0x31, 0x09,
	0x22, 0x44, 0x83, 0x67, 0xa7, 0x17, 0x99, 0x2a, 0x36, 0x75, 0xe0, 0x71, 0xbb, 0x93, 0x90, 0x8e,
	0xa6, 0x6d, 0xe4, 0xe3, 0x19, 0x92, 0xaa, 0x25, 0xb9, 0xb2, 0x7b, 0x77, 0x86, 0xf1, 0x00, 0x49,
	0x65, 0xfb, 0x7e, 0x78, 0x76, 0x86, 0x84, 0x71, 0x5b, 0x86, 0xaa, 0x6f, 0x46, 0xfa, 0xaf, 0xf9,
	0xac, 0x50, 0x7b, 0x75, 0x5b, 0x85, 0xe6, 0xd3, 0x27, 0x00, 0x00, 0xff, 0xff, 0x24, 0xda, 0xc8,
	0x5a, 0xc1, 0x00, 0x00, 0x00,
}
